### ISSUE TITLE
Upgrade to DocBook XSL 1.79.0

### ISSUE THREAD

**Issue by markcraig** [mimil/docbkx-tools#122]
Now that DocBook XSL 1.79.0 is released, it would be nice to test with the snapshot version of docbkx-tools so that we can provide feedback before the stable version is finished.

**Comment by mimil** [comment]
Hello,

I released docbkx-tools in 2.0.17-SNAPSHOT using latest 1.79.1 docbook xslt version. If you want to give it a try before I make a 2.0.17 release.

Regards,
Cedric

**Comment by markcraig** [comment]
Thanks very much. I have started to have a look at this today.

Most things seem to work fine. I'm having one problem that I haven't yet diagnosed resolving olinks in chunked HTML. My code that worked with 1.78.1 stylesheets no longer works, since it seems that <chunkBaseDir> is not supported in 1.79.1:

    Unable to execute mojo: 
      Unable to parse configuration of mojo com.agilejava.docbkx:docbkx-maven-plugin:2.0.17-SNAPSHOT:generate-html:
        Cannot find setter, adder nor field in com.agilejava.docbkx.maven.DocbkxHtmlMojo for 'chunkBaseDir'

It's probably not a big deal. Just need a little time with no interruptions to debug the problem.

**Comment by mimil** [comment]
Hello,

maybe this parameter disappeard, maybe docbkx plugin use this parameter (I
do not remember without looking at the code) so I have to find which other
parameter to use.

Cédric

**Comment by mimil** [comment]
from what I saw the issue is not in simple generation (html and chunked), I guess it is on your customization or class extends. I do not say that there is no issue to resolve on docbkx side.
I am currently releasing 2.0.17.

regards
Cedric
